outputs:
  selected_url:
    description: 'Selected YouTube URL'
  video_id:
    description: 'Video ID of the selected URL'
  comment_type:
    description: 'Type of comment (pull_request or issue)'
  number:
    description: 'Issue or PR number'
